name: "Jason Agel"
cacheVersion: "0017"

baseurl: "http://jasonagel.chrismatthias.com"
permalink: pretty
markdown: rdiscount
relative_permalinks: true
permalink:   /:categories/:title/
source:      .
destination: ./_site
layouts:     ./_layouts
include:     []
exclude:     ['.bundle', 'sass', 'CNAME', 'Gemfile', 'Gemfile.lock', 'Procfile', 'config.rb', '_config.yml', 'README.md']
keep_files:  ['.git']
timezone:    nil
encoding:    nil

future:      true
show_drafts: true
limit_posts: 20
pygments:    true

analytics:
  - google:
    id: "UA-XXXXXXX-1"

prose:
  rooturl: '_posts'
  siteurl: 'http://jasonagel.chrismatthias.com/'
  relativeLinks: 'http://jasonagel.chrismatthias.com/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/work:
      - name: "category"
        field:
          element: "hidden"
          value: "work"
      - name: "layout"
        field:
          element: "hidden"
          value: "work"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Recording"
              value: "recording"
            - name: "Mixing"
              value: "mixing"
            - name: "Production"
              value: "production"
    _posts/pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/:categories/:title/"