name: "Jason Agel"
cacheVersion: "0017"

author:
  - name: "Jason Agel"
  - email: "info@jasonagel.com"

baseurl: "/"
markdown: rdiscount
relative_permalinks: true
permalink:   /:categories/:title/
source:      .
destination: ./_site
layouts:     ./_layouts
include:     []
exclude:     ['devserver', 'config.ru', 'Procfile.local', 'vendor', '.bundle', 'sass', 'CNAME', 'Gemfile', 'Gemfile.lock', 'Procfile', 'config.rb', '_config.yml', 'README.md']
keep_files:  ['.git']
timezone:    nil
encoding:    nil

#assets:
#  compress:
#    js:   uglifier
#    css:  sass

future:      true
show_drafts: true
limit_posts: 20
pygments:    true

analytics:
  - google:
    id: "UA-XXXXXXX-1"

# picture:
#   source: media/_fullsize
#   output: generated
#   markup: picturefill
#   presets:
#     # Full width pictures
#     default:
#       ppi: [1, 1.5]
#       attr:
#         class: blog-full
#         itemprop: image
#       source_lrg:
#         media: "(min-width: 40em)"
#         width: 700
#       source_med:
#         media: "(min-width: 30em)"
#         width: 450
#       source_default:
#         width: 350
#         height: 200
#     # Half width pictures
#     half:
#       ppi: [1, 1.5]
#       attr:
#         data-location: "{{location}}"
#         data-active: nil
#       source_lrg:
#         media: "(min-width: 40em)"
#         width: 400
#       source_med:
#         media: "(min-width: 30em)"
#         width: 250
#       source_default:
#         width: 350
#     # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
#     gallery:
#       source_wide_hi:
#         media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
#         width: 900
#         height: 600
#       source_wide:
#         media: "(min-width: 40em)"
#         width: 600
#         height: 400
#       source_default:
#         width: 250
#         height: 250    

prose:
  rooturl: '_posts'
  siteurl: 'http://jasonagel.chrismatthias.com/'
  relativeLinks: 'http://jasonagel.chrismatthias.com/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/work:
      - name: "artist"
        field:
          element: "text"
          label: "Artist Name"
          value: ""
      - name: "album"
        field:
          element: "text"
          label: "Album Name"
          value: ""
      - name: "soundcloudwidget"
        field:
          element: "text"
          label: "Soundcloud URL"
          value: ""
          placeholder: "Soundcloud URL (https://soundcloud.com/XXXX)"
      - name: "mp3file"
        field:
          element: "text"
          label: "URL to mp3 file"
          value: ""
          placeholder: "Drag and drop MP3 file into post. Paste URL here."
      - name: "category"
        field:
          element: "hidden"
          value: "work"
      - name: "layout"
        field:
          element: "hidden"
          value: "work"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
          placeholder: "URL for this item"
      - name: "Contributions"
        field:
          element: "multiselect"
          label: "Your Contributions"
          placeholder: "Choose Contributions"
          options:
            - name: "Recording"
              value: "recording"
            - name: "Mixing"
              value: "mixing"
            - name: "Production"
              value: "production"
            - name: "Mastering"
              value: "mastering"
      - name: "audiotype"
        field:
          element: "multiselect"
          label: "Audio type"
          placeholder: "Is it an album? Single? What?"
          options:
            - name: "Audio Single"
              value: "single"
            - name: "Album"
              value: "album"
            - name: "Collaboration"
              value: "collaboration"
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured"
          value: false
    _posts/pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
