source "https://rubygems.org"

gem "zurb-foundation", "~> 3.2.5"
gem "jekyll"
gem "jekyll-assets"
gem "redcarpet"
gem "mini_magick"
gem "rdiscount"
gem "sinatra"
gem "thin"
gem "compass"
gem "uglifier"
gem "coffee-script"
